[package]
name = "pajbot3"
authors = [
    "Ruben Anders <ruben.anders@robotty.de>"
]
description = "Twitch moderation bot"
license = "AGPL-3.0-or-later"
repository = "https://github.com/pajbot/pajbot3"
keywords = ["twitch", "twitch-bot"]
categories = ["web-programming"]
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"
axum = "0.5"
chrono = { version = "0.4", features = ["serde"] }
clap = { version = "4", features = ["derive"] }
deadpool-postgres = { version = "0.10", features = ["rt_tokio_1"] }
enum-assoc = "0.3"
futures = "0.3"
http = "0.2"
humantime-serde = "1"
hyper = "0.14"
itertools = "0.10"
lazy_static = "1"
num_cpus = "1"
rand = "0.8"
refinery = { version = "0.8", features = ["tokio-postgres"] }
reqwest = { version = "0.11", features = ["rustls-tls-webpki-roots", "json"], default-features = false }
rustls = "0.20"
serde = { version = "1", features = ["derive"] }
thiserror = "1"
tokio = { version = "1", features = ["full"] }
tokio-postgres = { version = "0.7", features = ["with-chrono-0_4"] }
tokio-postgres-rustls = "0.9"
tokio-util = "0.7"
toml = "0.5"
tower-http = { version = "0.3", features = ["cors", "fs"] }
tracing = "0.1"
tracing-subscriber = "0.3"
webpki-roots = "0.22"
regex = "1"
