[package]
name = "pajbot3"
authors = [
    "Ruben Anders <ruben.anders@robotty.de>"
]
description = "Twitch moderation bot"
license = "AGPL-3.0-or-later"
repository = "https://github.com/pajbot/pajbot3"
keywords = ["twitch", "twitch-bot"]
categories = ["web-programming"]
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "4"
tokio = { version = "1", features = ["full"] }
tokio-postgres = { version = "0.7" }
toml = "0.5"
serde = { version = "1", features = ["derive"] }
humantime-serde = "1"
thiserror = "1"
itertools = "0.10"
tracing = "0.1"
tracing-subscriber = "0.3"
