[package]
name = "pajbot3"
authors = [
    "Ruben Anders <ruben.anders@robotty.de>"
]
description = "Twitch moderation bot"
license = "AGPL-3.0-or-later"
repository = "https://github.com/pajbot/pajbot3"
keywords = ["twitch", "twitch-bot"]
categories = ["web-programming"]
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { version = "1", features = ["backtrace"] }
async-trait = "0.1"
axum = "0.6"
chrono = { version = "0.4", features = ["serde"] }
clap = { version = "4", features = ["derive"] }
deadpool-postgres = { version = "0.10", features = ["rt_tokio_1"] }
enum-assoc = "1.1"
futures = "0.3"
http = "0.2"
humantime-serde = "1"
hyper = "0.14"
itertools = "0.11"
lazy_static = "1"
num_cpus = "1"
rand = "0.8"
redis = { version = "0.23.3", features = ["tokio", "tls-rustls-webpki-roots", "tokio-comp", "tokio-rustls-comp"] }
refinery = { version = "0.8", features = ["tokio-postgres"] }
regex = "1"
reqwest = { version = "0.11", features = ["rustls-tls-webpki-roots", "json"], default-features = false }
rustls = "0.21"
serde = { version = "1", features = ["derive"] }
serde_json = "1.0.107"
thiserror = "1"
tokio = { version = "1", features = ["full"] }
tokio-postgres = { version = "0.7", features = ["with-chrono-0_4"] }
tokio-postgres-rustls = "0.10"
tokio-rustls = "0.24.1"
tokio-util = "0.7"
toml = "0.8"
tower-http = { version = "0.4", features = ["cors", "fs"] }
tracing = "0.1"
tracing-subscriber = "0.3"
twitch-irc = { path = "/home/pajlada/git/twitch-irc-rs", version = "5.0.1", features = ["refreshing-token-rustls-webpki-roots", "transport-tcp-rustls-webpki-roots"], default-features = false }
twitch_oauth2 = "0.12.4"
webpki-roots = "0.25"

[target.'cfg(unix)'.dependencies]
hyperlocal = "0.8"
