[database]
# A connection string as described in https://www.postgresql.org/docs/current/libpq-connect.html#LIBPQ-CONNSTRING
path = "postgresql:///pajbot3"
#schema_search_path = "my_postgres_schema_name"

# Additional, optional options:
# These options control the database connection pool. By default, all these options are unset, with the default
# from sea-orm used.
#max_connections = <number>
#min_connections = <number>
# See https://docs.rs/humantime/latest/humantime/fn.parse_duration.html for supported duration strings.
#connect_timeout = "30s"
#idle_timeout = "30s"
#acquire_timeout = "30s"
#max_lifetime = "30s"
# Can be one of "Off", "Error", "Warn", "Info", "Debug" or "Trace".
#sqlx_logging_level = "Off"

[web]
# Specifies that address and port to bind to.
address = "127.0.0.1:2790"
# On unix systems, you can also use:
#path = "/var/run/pajbot3/web.sock"

[twitch_api]
client_id = "abcd"
client_secret = "abcd"
redirect_uri = "abcd"
