on: [push, pull_request]

name: Check documentation

jobs:
  build-and-test:
    name: Build and test documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0
      - uses: hecrj/setup-rust-action@v1
      - uses: actions/cache@v3
        with:
          path: |
            /usr/share/rust/.cargo/bin/mdbook
            /usr/share/rust/.cargo/registry/index/
            /usr/share/rust/.cargo/registry/cache/
            /usr/share/rust/.cargo/git/db/
            /usr/share/rust/.cargo/.crates.toml
            /usr/share/rust/.cargo/.crates2.json
          key: v4-mdbook-0.4
      - run: cargo install mdbook --vers "^0.4"
      - run: mdbook build docs
      - run: mdbook test docs
      - uses: actions/upload-artifact@v3
        with:
          name: book
          path: target/book
