on: [push, pull_request]

name: Check documentation

jobs:
  build-and-test:
    name: Build and test documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0
      - uses: hecrj/setup-rust-action@v1
      - uses: actions/cache@v2.1.6
        with:
          path: ~/.cargo
          key: v2-mdbook-0.4
      - run: cargo install mdbook --vers "^0.4"
      - run: mdbook build docs
      - run: mdbook test docs
      - run: find ~
      - uses: actions/upload-artifact@v2
        with:
          name: book
          path: |
            target/book
