on: [push, pull_request]

name: Check web code

jobs:
  build-and-test:
    name: Build and test web code (Node.js ${{ matrix.node-version }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3.3.0
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
        working-directory: ./web
      - run: npm run build
        working-directory: ./web
      - run: npm test
        working-directory: ./web
  check-format:
    name: Check formatting of web code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3.3.0
        with:
          node-version: 16.x
      - run: npm ci
        working-directory: ./web
        # npx --no-install uses the prettier version from package.json/package-lock.json
      - run: npx --no-install prettier --check .
        working-directory: ./web
