on: [push, pull_request]

name: Check documentation

jobs:
  build-and-test:
    name: Build and test documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          components: clippy
      - name: Rust Cache
        uses: Swatinem/rust-cache@v2
        with:
          key: "rust-cache-ubuntu"
      - run: cargo install mdbook --vers "^0.4"
      - run: mdbook build docs
      - run: mdbook test docs
      - uses: actions/upload-artifact@v2
        with:
          name: book
          path: target/book
